/**
 * Client-side PDF File Generator
 * Generates PDF files from legal drafts data
 */

import { legalDrafts, LegalDraft } from "../data/legalDrafts";

export function generatePDFContent(draft: LegalDraft): string {
  return `================================================================================
LEGAL DRAFT - ${draft.title.toUpperCase()}
================================================================================

BASIC INFORMATION
--------------------------------------------------------------------------------
Type: ${draft.type.toUpperCase()}
Court: ${draft.court}
State: ${draft.state}
Draft ID: ${draft.id}
Template ID: ${draft.template}

SITUATION
--------------------------------------------------------------------------------
${draft.situation}

SCENARIO
--------------------------------------------------------------------------------
${draft.scenario}

KEY LEGAL POINTS
--------------------------------------------------------------------------------
${draft.keyPoints.map((point, index) => `${index + 1}. ${point}`).join('\n')}

APPLICABLE SECTIONS
--------------------------------------------------------------------------------
${draft.applicableSections.join('\n')}

REQUIRED DOCUMENTS
--------------------------------------------------------------------------------
${draft.documents.map((doc, index) => `${index + 1}. ${doc}`).join('\n')}

SUCCESS FACTORS
--------------------------------------------------------------------------------
${draft.successFactors.map((factor, index) => `${index + 1}. ${factor}`).join('\n')}

IMPORTANT NOTES
--------------------------------------------------------------------------------
1. This is a template document and must be customized with your specific case details.
2. All dates, amounts, names, and case-specific information must be filled in.
3. Ensure all required documents are attached as per the list above.
4. File within the prescribed limitation period.
5. Consult with a qualified lawyer before filing.
6. Verify all legal provisions and court procedures.
7. Ensure proper court fees are paid.
8. Follow the format and structure as per court rules.

================================================================================
GENERATED BY: Land Acquisition LegalTech Suite
DATE: ${new Date().toLocaleDateString('en-IN', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
})}
================================================================================
`;
}

export function generatePDFFileName(draft: LegalDraft): string {
  const sanitizedTitle = draft.title
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  return `Draft_${draft.id}_${sanitizedTitle}.txt`;
}

export function downloadPDFFile(draft: LegalDraft): void {
  const content = generatePDFContent(draft);
  const fileName = generatePDFFileName(draft);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function viewPDFFile(draft: LegalDraft): void {
  const content = generatePDFContent(draft);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
  // Clean up after a delay
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

export function getPDFPath(draft: LegalDraft): string {
  const fileName = generatePDFFileName(draft);
  return `/drafts-pdf/${fileName}`;
}

// Generate all PDFs and return as downloadable files
export function generateAllPDFs(): void {
  legalDrafts.forEach(draft => {
    setTimeout(() => {
      downloadPDFFile(draft);
    }, draft.id * 100); // Stagger downloads
  });
}
