/**
 * PDF Generator Utility for Legal Drafts
 * Generates PDF documents for each legal draft
 */

import { LegalDraft } from "../data/legalDrafts";

export interface PDFInfo {
  draftId: number;
  fileName: string;
  path: string;
  size: string;
  createdAt: string;
}

// Generate PDF content for a draft
export const generatePDFContent = (draft: LegalDraft): string => {
  const content = `
LEGAL DRAFT - ${draft.title.toUpperCase()}

================================================================================
BASIC INFORMATION
================================================================================

Type: ${draft.type.toUpperCase()}
Court: ${draft.court}
State: ${draft.state}
Draft ID: ${draft.id}
Template ID: ${draft.template}

================================================================================
SITUATION
================================================================================

${draft.situation}

================================================================================
SCENARIO
================================================================================

${draft.scenario}

================================================================================
KEY LEGAL POINTS
================================================================================

${draft.keyPoints.map((point, index) => `${index + 1}. ${point}`).join('\n')}

================================================================================
APPLICABLE SECTIONS
================================================================================

${draft.applicableSections.join('\n')}

================================================================================
REQUIRED DOCUMENTS
================================================================================

${draft.documents.map((doc, index) => `${index + 1}. ${doc}`).join('\n')}

================================================================================
SUCCESS FACTORS
================================================================================

${draft.successFactors.map((factor, index) => `${index + 1}. ${factor}`).join('\n')}

================================================================================
DRAFT TEMPLATE STRUCTURE
================================================================================

This is a template draft for ${draft.type} filed in ${draft.court}, ${draft.state}.

SITUATION:
${draft.situation}

SCENARIO DETAILS:
${draft.scenario}

KEY POINTS TO INCLUDE:
${draft.keyPoints.map((point, index) => `${index + 1}. ${point}`).join('\n')}

APPLICABLE LEGAL PROVISIONS:
${draft.applicableSections.join('\n')}

SUPPORTING DOCUMENTS REQUIRED:
${draft.documents.map((doc, index) => `${index + 1}. ${doc}`).join('\n')}

FACTORS FOR SUCCESS:
${draft.successFactors.map((factor, index) => `${index + 1}. ${factor}`).join('\n')}

================================================================================
IMPORTANT NOTES
================================================================================

1. This is a template document and must be customized with your specific case details.
2. All dates, amounts, names, and case-specific information must be filled in.
3. Ensure all required documents are attached as per the list above.
4. File within the prescribed limitation period.
5. Consult with a qualified lawyer before filing.
6. Verify all legal provisions and court procedures.
7. Ensure proper court fees are paid.
8. Follow the format and structure as per court rules.

================================================================================
GENERATED BY: Land Acquisition LegalTech Suite
DATE: ${new Date().toLocaleDateString('en-IN', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
})}
================================================================================
`;

  return content;
};

// Generate PDF file name
export const generatePDFFileName = (draft: LegalDraft): string => {
  const sanitizedTitle = draft.title
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  return `Draft_${draft.id}_${sanitizedTitle}.pdf`;
};

// Get PDF path
export const getPDFPath = (draft: LegalDraft): string => {
  const fileName = generatePDFFileName(draft);
  return `/drafts-pdf/${fileName}`;
};

// Check if PDF exists (for browser environment)
export const checkPDFExists = async (path: string): Promise<boolean> => {
  try {
    const response = await fetch(path, { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
};

// Download PDF (generate and download)
export const downloadPDF = (draft: LegalDraft): void => {
  const content = generatePDFContent(draft);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = generatePDFFileName(draft).replace('.pdf', '.txt');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Get all PDF info (for listing)
export const getAllPDFInfo = (drafts: LegalDraft[]): PDFInfo[] => {
  return drafts.map(draft => ({
    draftId: draft.id,
    fileName: generatePDFFileName(draft),
    path: getPDFPath(draft),
    size: "~50-100 KB", // Estimated
    createdAt: new Date().toISOString()
  }));
};
