/**
 * Generate PDF Files for All 50 Legal Drafts
 * Run: node generate-pdfs.js
 */

const fs = require('fs');
const path = require('path');

// Read the legal drafts TypeScript file
const dataPath = path.join(__dirname, 'src/data/legalDrafts.ts');
const content = fs.readFileSync(dataPath, 'utf-8');

// Extract draft data using regex
function extractDrafts() {
  const drafts = [];
  const draftRegex = /{\s*id:\s*(\d+),[\s\S]*?title:\s*"([^"]+)",[\s\S]*?type:\s*"([^"]+)",[\s\S]*?court:\s*"([^"]+)",[\s\S]*?state:\s*"([^"]+)",[\s\S]*?situation:\s*"([^"]+)",[\s\S]*?scenario:\s*"([^"]+)",[\s\S]*?keyPoints:\s*\[([\s\S]*?)\],[\s\S]*?applicableSections:\s*\[([\s\S]*?)\],[\s\S]*?template:\s*"([^"]+)",[\s\S]*?documents:\s*\[([\s\S]*?)\],[\s\S]*?successFactors:\s*\[([\s\S]*?)\]\s*}/g;
  
  let match;
  while ((match = draftRegex.exec(content)) !== null) {
    const keyPoints = match[8].match(/"([^"]+)"/g)?.map(s => s.replace(/"/g, '')) || [];
    const sections = match[9].match(/"([^"]+)"/g)?.map(s => s.replace(/"/g, '')) || [];
    const documents = match[11].match(/"([^"]+)"/g)?.map(s => s.replace(/"/g, '')) || [];
    const factors = match[12].match(/"([^"]+)"/g)?.map(s => s.replace(/"/g, '')) || [];
    
    drafts.push({
      id: parseInt(match[1]),
      title: match[2],
      type: match[3],
      court: match[4],
      state: match[5],
      situation: match[6],
      scenario: match[7],
      keyPoints,
      applicableSections: sections,
      template: match[10],
      documents,
      successFactors: factors
    });
  }
  
  return drafts;
}

function generatePDFContent(draft) {
  return `================================================================================
LEGAL DRAFT - ${draft.title.toUpperCase()}
================================================================================

BASIC INFORMATION
--------------------------------------------------------------------------------
Type: ${draft.type.toUpperCase()}
Court: ${draft.court}
State: ${draft.state}
Draft ID: ${draft.id}
Template ID: ${draft.template}

SITUATION
--------------------------------------------------------------------------------
${draft.situation}

SCENARIO
--------------------------------------------------------------------------------
${draft.scenario}

KEY LEGAL POINTS
--------------------------------------------------------------------------------
${draft.keyPoints.map((point, index) => `${index + 1}. ${point}`).join('\n')}

APPLICABLE SECTIONS
--------------------------------------------------------------------------------
${draft.applicableSections.join('\n')}

REQUIRED DOCUMENTS
--------------------------------------------------------------------------------
${draft.documents.map((doc, index) => `${index + 1}. ${doc}`).join('\n')}

SUCCESS FACTORS
--------------------------------------------------------------------------------
${draft.successFactors.map((factor, index) => `${index + 1}. ${factor}`).join('\n')}

IMPORTANT NOTES
--------------------------------------------------------------------------------
1. This is a template document and must be customized with your specific case details.
2. All dates, amounts, names, and case-specific information must be filled in.
3. Ensure all required documents are attached as per the list above.
4. File within the prescribed limitation period.
5. Consult with a qualified lawyer before filing.
6. Verify all legal provisions and court procedures.
7. Ensure proper court fees are paid.
8. Follow the format and structure as per court rules.

================================================================================
GENERATED BY: Land Acquisition LegalTech Suite
DATE: ${new Date().toLocaleDateString('en-IN', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
})}
================================================================================
`;
}

function generateFileName(draft) {
  const sanitizedTitle = draft.title
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  return `Draft_${draft.id}_${sanitizedTitle}.txt`;
}

async function main() {
  console.log('📄 Generating PDF files for all 50 legal drafts...\n');

  const draftsPdfPath = path.join(__dirname, 'public/drafts-pdf');
  
  // Ensure directory exists
  if (!fs.existsSync(draftsPdfPath)) {
    fs.mkdirSync(draftsPdfPath, { recursive: true });
    console.log('✅ Created drafts-pdf directory');
  }

  try {
    const drafts = extractDrafts();
    console.log(`📊 Found ${drafts.length} drafts to process\n`);

    let generated = 0;
    for (const draft of drafts) {
      try {
        const pdfContent = generatePDFContent(draft);
        const fileName = generateFileName(draft);
        const filePath = path.join(draftsPdfPath, fileName);
        
        fs.writeFileSync(filePath, pdfContent, 'utf-8');
        generated++;
        
        if (generated % 10 === 0) {
          console.log(`⏳ Generated ${generated}/${drafts.length} files...`);
        }
      } catch (error) {
        console.error(`❌ Error generating file for draft ${draft.id}:`, error.message);
      }
    }

    console.log(`\n✅ Successfully generated ${generated} PDF files!`);
    console.log(`📁 Files saved in: ${draftsPdfPath}`);
    console.log(`\n📝 Note: Files are saved as .txt format for now.`);
    console.log(`   They can be converted to PDF using any text-to-PDF converter.`);
  } catch (error) {
    console.error('❌ Error:', error.message);
    console.log('\n💡 Alternative: Using fallback method to generate files...');
    
    // Fallback: Generate from known structure
    const fallbackDrafts = [];
    for (let i = 1; i <= 50; i++) {
      const type = i <= 20 ? 'reference' : i <= 40 ? 'appeal' : 'review';
      fallbackDrafts.push({
        id: i,
        title: `Legal Draft ${i} - ${type}`,
        type,
        court: 'High Court',
        state: 'State',
        situation: 'Situation description',
        scenario: 'Detailed scenario',
        keyPoints: ['Key point 1', 'Key point 2'],
        applicableSections: ['Section 18 of LAA 1894'],
        template: `TEMPLATE_${i}`,
        documents: ['Document 1', 'Document 2'],
        successFactors: ['Factor 1', 'Factor 2']
      });
    }
    
    let generated = 0;
    for (const draft of fallbackDrafts) {
      const pdfContent = generatePDFContent(draft);
      const fileName = generateFileName(draft);
      const filePath = path.join(draftsPdfPath, fileName);
      fs.writeFileSync(filePath, pdfContent, 'utf-8');
      generated++;
    }
    
    console.log(`✅ Generated ${generated} fallback files`);
  }
}

main().catch(console.error);
